@Library("k8sagent") _
pipeline {
  agent {
    kubernetes(k8sagent(name: 'maven'))
      //maven-homeVolume persistentVolumeClaimMaven-homeVolume(claimName: 'jenkins-cache-pvc', readOnly: false)
  }
  tools {
     maven 'MAVEN'
   }
    stages {
        stage('Build') {
            steps {
                sh 'mvn -B -DskipTests clean package'
            }
        }
        stage('Test') {
            steps {
                sh 'pwd'
                sh 'ls -la'
                sh 'mvn test'
            }
            post {
                always {
                    junit 'target/surefire-reports/*.xml'
                }
            }
        }
        stage('Deliver') {
            steps {
                sh './jenkins/scripts/deliver.sh'
                }
            }
        }
    }
